# Analysing dynamics structures 

## Imports

In [46]:
import numpy as np
import MDAnalysis as mda
import MDAnalysis.analysis.rms

## Read in `.dcd` files

In [76]:
frames = []
with mda.lib.formats.libdcd.DCDFile("data/ligand_10.dcd") as trajectory_file:
    for frame in trajectory_file:
        frames.append(frame)

In [78]:
frames[0]

DCDFrame(xyz=array([[24.866346, 44.733044, 28.16643 ],
       [24.410322, 44.670948, 29.66312 ],
       [23.440842, 45.386215, 30.005636],
       ...,
       [72.48585 , 82.18371 , 44.732986],
       [71.44646 , 82.92164 , 45.549152],
       [47.45111 , 31.10867 , 37.421722]], dtype=float32), unitcell=array([72.10255277,  0.33333333, 72.10255277, -0.33333333,  0.33333333,
       72.10255277]))

In [80]:
frames[-1].xyz

array([[22.283272 , 40.22844  , 29.746763 ],
       [22.492094 , 39.965683 , 31.215078 ],
       [22.761395 , 38.803448 , 31.5883   ],
       ...,
       [ 3.895906 , 47.484047 , 38.290794 ],
       [ 5.1732435, 47.848766 , 37.56528  ],
       [22.501585 , 41.853546 , 50.207954 ]], dtype=float32)

In [99]:
universe = mda.Universe("data/ligand_10.prmtop","data/ligand_10.dcd")

In [100]:
protein = universe.select_atoms("protein")

In [101]:
backbone = protein.select_atoms("backbone")
backbone

<AtomGroup with 1035 atoms>

In [103]:
a_coordinates = backbone.positions.copy()
universe.trajectory[-1]
b_coordinates = backbone.positions.copy()
rmsd_protein = mda.analysis.rms.rmsd(a_coordinates, b_coordinates, center=True)

In [104]:
a_coordinates

array([[22.492094, 39.965683, 31.215078],
       [22.761395, 38.803448, 31.5883  ],
       [22.195879, 40.978607, 32.028038],
       ...,
       [48.55381 , 68.310776, 27.013397],
       [47.95    , 67.73146 , 26.139156],
       [47.929115, 69.25346 , 27.705505]], dtype=float32)

In [105]:
b_coordinates

array([[22.492094, 39.965683, 31.215078],
       [22.761395, 38.803448, 31.5883  ],
       [22.195879, 40.978607, 32.028038],
       ...,
       [48.55381 , 68.310776, 27.013397],
       [47.95    , 67.73146 , 26.139156],
       [47.929115, 69.25346 , 27.705505]], dtype=float32)

In [106]:
rmsd_protein

0.0

In [108]:
reference_universe = mda.Universe("data/ligand_10.prmtop", frames[0].xyz)
universe = mda.Universe("data/ligand_10.prmtop","data/ligand_10.dcd")

reference_protein = reference_universe.select_atoms("protein")
protein = universe.select_atoms("protein")
rmsd_protein = mda.analysis.rms.RMSD(protein, reference)
rmsd_protein.run()

In [109]:
import matplotlib.pyplot as plt
rmsd_result = rmsd_protein.results.rmsd.T   # transpose makes it easier for plotting
print(rmsd_result)
# time = rmsd_result[1]
# fig = plt.figure(figsize=(4,4))
# ax = fig.add_subplot(111)
# ax.plot(time, rmsd_result[2], 'k-',  label="all")
# ax.legend(loc="best")
# ax.set_xlabel("time (ps)")
# ax.set_ylabel(r"RMSD ($\AA$)")
# fig.savefig("rmsd_all_CORE_LID_NMP_ref1AKE.pdf")

[[0.00000000e+00 1.00000000e+00 2.00000000e+00 ... 4.99700000e+03
  4.99800000e+03 4.99900000e+03]
 [0.00000000e+00 4.88882123e-05 9.77764246e-05 ... 2.44294397e-01
  2.44343285e-01 2.44392173e-01]
 [4.10827508e-06 1.66443008e+01 1.94511942e+01 ... 4.96506256e+01
  4.96654232e+01 4.96138932e+01]]
